### ISSUE TITLE
Add 'priority' feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#103]
In bugbug/bug_features.py

**Comment by sbeesm** [comment]
I need to implement a feature extractor class `priority` to extract bug priorities right?

**Comment by marco-c** [comment]
Correct!

**Comment by sbeesm** [comment]
I'm not able to run the project locally. I've installed all the requirements but it shows an error:
```
HP@LAPTOP-6V5RSGD0 MINGW64 /f/COMPILED/Git/bugbug (master)
$ python -i run.py --train
Traceback (most recent call last):
  File "run.py", line 25, in <module>
    from bugbug.models.bug import BugModel
  File "F:\COMPILED\Git\bugbug\bugbug\models\bug.py", line 14, in <module>
    from bugbug.model import Model
  File "F:\COMPILED\Git\bugbug\bugbug\model.py", line 7, in <module>
    import shap
  File "C:\Anaconda3\lib\site-packages\shap\__init__.py", line 11, in <module>
    from .plots.summary import summary_plot
  File "C:\Anaconda3\lib\site-packages\shap\plots\summary.py", line 13, in <module>
    from . import colors
  File "C:\Anaconda3\lib\site-packages\shap\plots\colors.py", line 5, in <module>
    import skimage.color
  File "C:\Anaconda3\lib\site-packages\skimage\__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Anaconda3\lib\site-packages\skimage\util\__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "C:\Anaconda3\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'
```

Please help.

**Comment by marco-c** [comment]
@sbeesm please open a separate issue, as your problem is unrelated to this issue.

**Comment by sbeesm** [comment]
The error was due to the incompatible versions of scikit-image and numpy.
I've opened an issue #120 related to this.
