### ISSUE TITLE
Operating System requirement

### ISSUE THREAD

**Issue by Nathan-Wisner** [mozilla/bugbug#1139]
When trying to install the application on Windows with the `pip install -r requirements.txt` command greets me with plenty of errors around rs_parsepatch and cannot seem to build despite having only python 3.8 installed. Is there something I am missing? Am I supposed to be on Linux or should this work on Windows? 

I have followed the instructions for installing several times with no avail.

**Comment by marco-c** [comment]
I have never tested on Windows, so it's likely that something might be broken. rs_parsepatch can't be installed on Mac either (https://github.com/mozilla/pyo3-parsepatch/issues/4). You can open an issue on that repo with more details about the error.

So, in summary, the easiest thing to do is using Linux, either via a VM or WSL or (better) a bare metal installation.

**Comment by abhaykatheria** [comment]
```
  Missing build time requirements in pyproject.toml for orjson==2.1.3 from https://files.pythonhosted.org/packages/55/73/74f2cf51686630997d0550a02c3119336941daf17f1e713c448bce1dd508/orjson-2.1.3.tar.gz#sha256=b1ff8441050c11e9d4cee9b80b0dfc1f8eb8c0827e78037885e58f4cf34e34ea (from -r requirements.txt (line 7)): 'setuptools' and 'wheel'.
  This version of pip does not implement PEP 517 so it cannot build a wheel without 'setuptools' and 'wheel'.
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\abhay\appdata\local\programs\python\python37-32\lib\tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\abhay\\AppData\\Local\\Temp\\pip-install-ixd2sdhc\\orjson\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\abhay\AppData\Local\Temp\pip-install-ixd2sdhc\orjson\
```

this is the error i get when i try it installing on windows

**Comment by marco-c** [comment]
> this is the error i get when i try it installing on windows

It seems like an error while installing orjson, you should file an issue on the orjson repo.

**Comment by Nathan-Wisner** [comment]
When running `python3 -m pip install -r requirements.txt` on Linux, it collects the packages correctly, however, when installing the collected packages it labels a 'Segmentation fault (core dumped)'

I attempted to ignore this, however, when running `python3 -m scripts.trainer`, it gives an error about a lack of arguments. I attempted to fill this with `python3 -m scripts.trainer bug` there is the error that `Attribute Error: 'BugModel' object has no attribute 'get_labels`.

There seem to be some missing items around the installing process as this is a new virtual machine with Ubuntu on Python 3.8 and the code is as of 11/28/19.

Thanks all for your help so far!

**Comment by marco-c** [comment]
Could you try `python3 -m scripts.trainer defect` instead? `bug` is not supposed to be trainable (the fact that it is accepted as an argument to trainer is a bug).

**Comment by Nathan-Wisner** [comment]
It gives an error `json.decoder.JSONDecodeError: EOF while parsing a string at line 1 column 4101 line 1 column 1 (char 0)`

**Comment by marco-c** [comment]
Could you paste the full stack trace?

**Comment by Nathan-Wisner** [comment]
`python3 -m scripts.trainer defect
/home/nathan/.local/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
2019-11-29 16:21:54,581:INFO:bugbug.db:Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.relman.bugbug.data_bugs.latest/artifacts/public/bugs.json.zst to data/bugs.json.zst
2019-11-29 16:21:55,054:INFO:__main__:Training *defect* model
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nathan/Documents/bugbug/scripts/trainer.py", line 143, in <module>
    main()
  File "/home/nathan/Documents/bugbug/scripts/trainer.py", line 139, in main
    retriever.go(args)
  File "/home/nathan/Documents/bugbug/scripts/trainer.py", line 58, in go
    metrics = model_obj.train(limit=args.limit)
  File "/home/nathan/Documents/bugbug/bugbug/model.py", line 319, in train
    classes, self.class_names = self.get_labels()
  File "/home/nathan/Documents/bugbug/bugbug/models/defect.py", line 251, in get_labels
    return (self.get_bugbug_labels("bug"), [0, 1])
  File "/home/nathan/Documents/bugbug/bugbug/models/defect.py", line 173, in get_bugbug_labels
    for bug in bugzilla.get_bugs():
  File "/home/nathan/Documents/bugbug/bugbug/bugzilla.py", line 82, in get_bugs
    for bug in db.read(BUGS_DB)
  File "/home/nathan/Documents/bugbug/bugbug/bugzilla.py", line 81, in <genexpr>
    bug
  File "/home/nathan/Documents/bugbug/bugbug/db.py", line 199, in read
    for elem in store.read():
  File "/home/nathan/Documents/bugbug/bugbug/db.py", line 137, in read
    yield orjson.loads(line)
json.decoder.JSONDecodeError: EOF while parsing a string at line 1 column 4104: line 1 column 1 (char 0)
`

**Comment by marco-c** [comment]
Aaargh, my eyes, you copied the whole thing without newlines :package: 

Anyway, it seems like your bugs DB was not correctly downloaded. Try removing it (rm data/bugs.json*) and re-running the command.

**Comment by Nathan-Wisner** [comment]
After removing it and reinstalling both of the files i get results that seem to get farther, i've posted the error below

```
2019-11-29 19:48:36,779:INFO:__main__:Training *defect* model

X: (34151, 22917), y: (34151,)
/home/nathan/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:530: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nathan/Documents/bugbug/scripts/trainer.py", line 143, in <module>
    main()
  File "/home/nathan/Documents/bugbug/scripts/trainer.py", line 139, in main
    retriever.go(args)
  File "/home/nathan/Documents/bugbug/scripts/trainer.py", line 58, in go
    metrics = model_obj.train(limit=args.limit)
  File "/home/nathan/Documents/bugbug/bugbug/model.py", line 355, in train
    scores = cross_validate(pipeline, X_train, y_train, scoring=scorings, cv=5)
  File "/home/nathan/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 232, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/nathan/.local/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/nathan/.local/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/nathan/.local/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/nathan/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/home/nathan/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/home/nathan/.local/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/nathan/.local/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/nathan/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 516, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/nathan/.local/lib/python3.6/site-packages/imblearn/pipeline.py", line 238, in fit
    Xt, yt, fit_params = self._fit(X, y, **fit_params)
  File "/home/nathan/.local/lib/python3.6/site-packages/imblearn/pipeline.py", line 201, in _fit
    cloned_transformer, X, y, **fit_params_steps[name])
  File "/home/nathan/.local/lib/python3.6/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/home/nathan/.local/lib/python3.6/site-packages/imblearn/pipeline.py", line 582, in _fit_resample_one
    X_res, y_res = sampler.fit_resample(X, y, **fit_params)
  File "/home/nathan/.local/lib/python3.6/site-packages/imblearn/base.py", line 84, in fit_resample
    output = self._fit_resample(X, y)
  File "/home/nathan/.local/lib/python3.6/site-packages/imblearn/over_sampling/_smote.py", line 336, in _fit_resample
    return self._sample(X, y)
  File "/home/nathan/.local/lib/python3.6/site-packages/imblearn/over_sampling/_smote.py", line 352, in _sample
    self.nn_m_, X_class, class_sample, y, kind='danger')
  File "/home/nathan/.local/lib/python3.6/site-packages/imblearn/over_sampling/_smote.py", line 213, in _in_danger_noise
    x = nn_estimator.kneighbors(samples, return_distance=False)[:, 1:]
  File "/home/nathan/.local/lib/python3.6/site-packages/sklearn/neighbors/base.py", line 434, in kneighbors
    **kwds))
  File "/home/nathan/.local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1448, in pairwise_distances_chunked
    n_jobs=n_jobs, **kwds)
  File "/home/nathan/.local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1588, in pairwise_distances
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "/home/nathan/.local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1206, in _parallel_pairwise
    return func(X, Y, **kwds)
  File "/home/nathan/.local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 273, in euclidean_distances
    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)
  File "/home/nathan/.local/lib/python3.6/site-packages/sklearn/utils/extmath.py", line 137, in safe_sparse_dot
    ret = a * b
  File "/home/nathan/.local/lib/python3.6/site-packages/scipy/sparse/base.py", line 481, in __mul__
    return self._mul_sparse_matrix(other)
  File "/home/nathan/.local/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 516, in _mul_sparse_matrix
    indices = np.empty(nnz, dtype=idx_dtype)
MemoryError: Unable to allocate array with shape (134195846,) and data type int32

```

**Comment by Nathan-Wisner** [comment]
I think i fixed the problems with it as long as I don't let my virtual machine fall asleep.

I'll update another thread if there are problems from this point on but from now on we could maybe specify that Mac and Windows don't work as of now.
