### ISSUE TITLE
`hg: unknown command 'robustcheckout'\n(did you mean checkout?)` on Heroku

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1341]
```
2020-02-29T11:31:20.008484+00:00 app[worker.1]: Traceback (most recent call last):
2020-02-29T11:31:20.008503+00:00 app[worker.1]:   File "/usr/local/bin/bugbug-http-worker", line 8, in <module>
2020-02-29T11:31:20.008504+00:00 app[worker.1]:     sys.exit(main())
2020-02-29T11:31:20.008505+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/bugbug_http/worker.py", line 23, in main
2020-02-29T11:31:20.008506+00:00 app[worker.1]:     bugbug_http.boot.boot_worker()
2020-02-29T11:31:20.008506+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/bugbug_http/boot.py", line 20, in boot_worker
2020-02-29T11:31:20.008506+00:00 app[worker.1]:     repository.clone(repo_dir)
2020-02-29T11:31:20.008507+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/bugbug/repository.py", line 971, in clone
2020-02-29T11:31:20.008508+00:00 app[worker.1]:     raise hglib.error.CommandError(cmd, proc.returncode, out, err)
2020-02-29T11:31:20.008509+00:00 app[worker.1]: hglib.error.CommandError: (255, b'', b"hg: unknown command 'robustcheckout'\n(did you mean checkout?)")
```

**Comment by marco-c** [comment]
The hgrc is probably not being picked up, it's strange though as it works normally with other tasks based on the bugbug-commit-retrieval image.

**Comment by La0** [comment]
Maybe the new image was not properly built, i get errors due to `defectenhancementtaskmodel` being missing.

**Comment by marco-c** [comment]
> Maybe the new image was not properly built, i get errors due to defectenhancementtaskmodel being missing.

This is due to a more recent change, 3eee2f8c7a567ff39972fb5d07a051562a9c9d84.
