### ISSUE TITLE
Fix confusion matrix for multilabel classification.

### ISSUE THREAD

**Issue by ayush-1506** [mozilla/bugbug#1373]
Error seems to be coming from https://github.com/mozilla/bugbug/blob/master/bugbug/model.py#L504 . Stack trace while running the bugtype model:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ayush99/github/bugbug/bugbug/model.py", line 504, in train
    y_test[classified_indices], np.asarray(y_pred_filter)
  File "/Users/ayush99/github/bbug/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 396, in multilabel_confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/Users/ayush99/github/bbug/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 81, in _check_targets
    "and {1} targets".format(type_true, type_pred))
ValueError: Classification metrics can't handle a mix of multilabel-indicator and binary targets```

**Comment by ayush-1506** [comment]
@chidauri Since you worked on the confusion metric part, would you be interested in taking this up? Let me know else I'll give this a shot.

**Comment by chidauri** [comment]
@ayush-1506 Sure i can take this up.

**Comment by ayush-1506** [comment]
Thanks, would be great if you could fix it so we could test all multilabel models.

**Comment by chidauri** [comment]
@ayush-1506 hey, i just ran the bugtype model but couldn't find any such problem, i used 20000 limit. Can you try it again(maybe also try with 20000 as limit)?

**Comment by ayush-1506** [comment]
Ah, that's weird. I'll see what might have caused this for me.
