### ISSUE TITLE
Running docker-compose build fails at ensure_models.sh

### ISSUE THREAD

**Issue by armenzg** [mozilla/bugbug#1549]
```shell
Step 12/13 : RUN bash /code/http_service/ensure_models.sh
 ---> Running in c26e6e3ae3f1
+ '[' '' == 0 ']'
+ python -m bugbug_http.download_models
2020-05-06 19:57:50,567:INFO:matplotlib.font_manager:generated new fontManager
2020-05-06 19:57:50,961:INFO:bugbug.utils:Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.relman.bugbug.train_defectenhancementtask.v0.0.280/artifacts/public/defectenhancementtaskmodel.zst...
2020-05-06 19:58:06,562:INFO:bugbug.utils:Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.relman.bugbug.train_component.v0.0.280/artifacts/public/componentmodel.zst...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/bugbug_http/download_models.py", line 34, in <module>
    download_models()
  File "/usr/local/lib/python3.8/site-packages/bugbug_http/download_models.py", line 17, in download_models
    utils.download_model(model_name)
  File "/usr/local/lib/python3.8/site-packages/bugbug/utils.py", line 223, in download_model
    updated = download_check_etag(url)
  File "/usr/local/lib/python3.8/site-packages/bugbug/utils.py", line 191, in download_check_etag
    r.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://community-tc.services.mozilla.com/api/index/v1/task/project.relman.bugbug.train_component.v0.0.280/artifacts/public/componentmodel.zst
ERROR: Service 'bugbug-http-service-bg-worker' failed to build: The command '/bin/sh -c bash /code/http_service/ensure_models.sh' returned a non-zero code: 1
```

**Comment by marco-c** [comment]
It's because a model is not yet available for version 0.0.280. You can either force an older version with defining `TAG`, or avoid checking models defining `CHECK_MODELS` to 0.
