### ISSUE TITLE
Don't fail when analyzing old revisions

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1735]
This doesn't normally happen, as pushed revisions are always new revisions, but it can happen in two situations:
1) While developing taskgraph code on top of an old revision and testing optimization;
2) When trying to rerun an old decision task.

```
 Traceback (most recent call last): 
   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 883, in perform_job 
     rv = job.perform() 
   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 657, in perform 
     self._result = self._execute() 
   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 663, in _execute 
     return self.func(*self.args, **self.kwargs) 
   File "/usr/local/lib/python3.8/site-packages/bugbug_http/models.py", line 139, in schedule_tests 
     commits = repository.download_commits( 
   File "/usr/local/lib/python3.8/site-packages/bugbug/repository.py", line 1061, in download_commits 
     calculate_experiences(commits, save) 
   File "/usr/local/lib/python3.8/site-packages/bugbug/repository.py", line 930, in calculate_experiences 
     update_experiences("reviewer", day, commit.reviewers) 
   File "/usr/local/lib/python3.8/site-packages/bugbug/repository.py", line 796, in update_experiences 
     timespan_exps = tuple( 
   File "/usr/local/lib/python3.8/site-packages/bugbug/repository.py", line 797, in <genexpr> 
     exp - exp_queues[i][day - EXPERIENCE_TIMESPAN] 
   File "/usr/local/lib/python3.8/site-packages/bugbug/utils.py", line 332, in __getitem__ 
     assert ( 
 AssertionError: Can't get a day (3521) from earlier than start day (3523)
```

**Comment by marco-c** [comment]
Two possible solutions:
- have a custom "revision" number that is stored in the experiences DB and is shared between repos;
- partially revert 5c61636ffc0eab284a0f849d43db6d3eb6b1d02c and go back to use push date.
