### ISSUE TITLE
Can not train DevDocNeeded model

### ISSUE THREAD

**Issue by ranpox** [mozilla/bugbug#194]
I got AssertionError when I executed `python run.py --train --goal devdocneeded`.
```
Traceback (most recent call last):
  File "run.py", line 68, in <module>
    model = model_class(args.lemmatization)
  File "/Users/xxxxxx/bugbug/bugbug/models/devdocneeded.py", line 52, in __init__
    ('bug_extractor', bug_features.BugExtractor(feature_extractors, cleanup_functions, rollback=True, rollback_when=self.rollback, commit_data=True)),
  File "/Users/xxxxxx/bugbug/bugbug/bug_features.py", line 340, in __init__
    assert self.commit_map is None or len(self.commit_map) > 0
AssertionError
```
It seems that the length of self.commit_map is 0 because all `bug_id` in commit.json are "".

**Comment by marco-c** [comment]
I've updated the commits database, can you remove it manually and re-run, it should work now.
