### ISSUE TITLE
Improve documentation about how to use repository.py

### ISSUE THREAD

**Issue by saurabhdaalia** [mozilla/bugbug#202]
I am facing this particular issue when running repository.py 
@marco-c  @ayush1999 

```
Traceback (most recent call last):
  File "bugbug/bugbug/repository.py", line 203, in <module>
    download_commits(args.repository_dir, two_years_and_six_months_ago)
  File "bugbug/bugbug/repository.py", line 129, in download_commits
    first_rev = get_rev(hg, date_from)
  File "bugbug/bugbug/repository.py", line 123, in get_rev
    return hg.log(revrange='pushdate("{}")'.format(date.strftime('%Y-%m-%d')), limit=1)[0].node.decode('utf-8')
  File "C:\ProgramData\Anaconda3\lib\site-packages\hglib\client.py", line 1102, in log
    out = self.rawcommand(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hglib\client.py", line 263, in rawcommand
    raise error.CommandError(args, ret, out, err)
hglib.error.CommandError: (255, b'', b'hg: parse error: unknown identifier: pushdate\n(did you mean date?)')

```

**Comment by ayush1999** [comment]
Have you added `pushlog`, `hgmo` to the extensions in your .hgrc file?

**Comment by marco-c** [comment]
See https://github.com/mozilla/bugbug/issues/186#issuecomment-468366704

We need to improve the documentation in the README.

**Comment by saurabhdaalia** [comment]
I added the extensions to `hgrc` file. 
I am getting an empty list error when running the `repository.py`

```
Traceback (most recent call last):
  File "repository.py", line 203, in <module>
    download_commits(args.repository_dir, two_years_and_six_months_ago)
  File "repository.py", line 129, in download_commits
    first_rev = get_rev(hg, date_from)
  File "repository.py", line 123, in get_rev
    return hg.log(revrange='pushdate("{}")'.format(date.strftime('%Y-%m-%d')), limit=1)[0].node.decode('utf-8')
IndexError: list index out of range
```
Error still remains after runnning `hg pull` and `hg up` commands too

**Comment by marco-c** [comment]
Try running `hg log -r 'pushdate("2018-01-01")'` in your terminal (in the directory where you cloned the mercurial repository). What is the output?

**Comment by ayush1999** [comment]
@marco-c Can I write a quick fix for this in the readme?

**Comment by marco-c** [comment]
Sure, thanks!

**Comment by saurabhdaalia** [comment]
@marco-c 

```
$ hg log -r 'pushdate("2018-01-01")'
*** failed to import extension mozext from C:\Users\Saurabh Daalia\.mozbuild\version-control-tools\hgext\mozext: No module named Cookie
changeset:   397531:4b1c0f010623
user:        ffxbld
date:        Sun Dec 31 22:11:16 2017 -0800
summary:     No bug, Automated HSTS preload list update from host bld-linux64-spot-033 - a=hsts-update

changeset:   397532:eaf0381dcd0b
user:        ffxbld
date:        Sun Dec 31 22:11:20 2017 -0800
summary:     No bug, Automated HPKP preload list update from host bld-linux64-spot-033 - a=hpkp-update

changeset:   397533:aa6fd6d2a7ce
user:        Sebastian Hengst <archaeopteryx@coole-files.de>
date:        Mon Jan 01 13:20:57 2018 +0100
summary:     Bug 1427510 - Use current year as expiration year in credit card test to fix perma failure. r=permafail-fix a=permafail-fix

changeset:   397534:27037bf80310
user:        Sebastian Hengst <archaeopteryx@coole-files.de>
date:        Mon Jan 01 13:40:38 2018 +0100
summary:     Bug 1427510 - Use current year as expiration year in credit card test to fix perma failure: fix eslint issue. r=eslint-fix a=eslint-fix

changeset:   397535:a0df091c3697
user:        Sebastian Hengst <archaeopteryx@coole-files.de>
date:        Mon Jan 01 14:55:50 2018 +0100
summary:     Bug 1427510 - Disable perma failing browser_editCreditCardDialog.js until it gets fixed. r=permafail-fix a=permafail-fix
```

**Comment by marco-c** [comment]
Try to print `'pushdate("{}")'.format(date.strftime('%Y-%m-%d'))` and `hg.log(revrange='pushdate("{}")'.format(date.strftime('%Y-%m-%d')), limit=1)` in repository.py and post the output here.

**Comment by saurabhdaalia** [comment]
@marco-c 
Following snippet included output of `pushdate` and `hg.log` command. Also, on running reporitory.py this time, I get another error.  😓

```
pushdate("2016-09-06")
[(b'312651', b'edeae4a294a74581aed5056070e991f0b1cb2e10', b'', b'default', b'Luca Greco <lgreco@mozilla.com>', b"Bug 1252215 - [webext] LegacyExtensionsUtils JSM module and LegacyExtensionContext helper. r=aswan,kmag\n\n- this new module contains helpers to be able to receive connections\n  originated from a webextension context from a legacy extension context\n  (implemented by the `LegacyExtensionContext` class exported from\n  this new jsm module)\n\n- two new test files (an xpcshell-test and a mochitest-browser) ensures that the LegacyExtensionContext can receive a Port\n  object and exchange messages with a background page and a content script (the content script test\n  is in a different test file because it doesn't currently work on android, because it needs\n  the browser.tabs API and the TabManager internal helper)\n\nMozReview-Commit-ID: DS1NTXk0fB6", datetime.datetime(2016, 8, 24, 22, 1, 36))]
Mining commits using 4 processes...
  0%|                                                                                       | 0/143319 [00:00<?, ?it/s]concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 191, in _process_chunk
    return [fn(*args) for args in chunk]
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 191, in <listcomp>
    return [fn(*args) for args in chunk]
  File "C:\Users\Saurabh Daalia\Desktop\bugbug\bugbug\repository.py", line 57, in _transform
    'author_experience': author_experience[commit],
KeyError: Commit(node=b'edeae4a294a74581aed5056070e991f0b1cb2e10', author=b'Luca Greco <lgreco@mozilla.com>', desc=b"Bug 1252215 - [webext] LegacyExtensionsUtils JSM module and LegacyExtensionContext helper. r=aswan,kmag\n\n- this new module contains helpers to be able to receive connections\n  originated from a webextension context from a legacy extension context\n  (implemented by the `LegacyExtensionContext` class exported from\n  this new jsm module)\n\n- two new test files (an xpcshell-test and a mochitest-browser) ensures that the LegacyExtensionContext can receive a Port\n  object and exchange messages with a background page and a content script (the content script test\n  is in a different test file because it doesn't currently work on android, because it needs\n  the browser.tabs API and the TabManager internal helper)\n\nMozReview-Commit-ID: DS1NTXk0fB6", date=datetime.datetime(2016, 8, 24, 22, 1, 36), bug=b'', ever_backedout=False, author_email=b'lgreco@mozilla.com')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bugbug/repository.py", line 206, in <module>
    download_commits(args.repository_dir, two_years_and_six_months_ago)
  File "bugbug/repository.py", line 179, in download_commits
    db.write(COMMITS_DB, commits)
  File "C:\Users\Saurabh Daalia\Desktop\bugbug\bugbug\db.py", line 60, in write
    for bug in bugs:
  File "C:\Users\Saurabh Daalia\AppData\Roaming\Python\Python37\site-packages\tqdm\_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 476, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
KeyError: Commit(node=b'edeae4a294a74581aed5056070e991f0b1cb2e10', author=b'Luca Greco <lgreco@mozilla.com>', desc=b"Bug 1252215 - [webext] LegacyExtensionsUtils JSM module and LegacyExtensionContext helper. r=aswan,kmag\n\n- this new module contains helpers to be able to receive connections\n  originated from a webextension context from a legacy extension context\n  (implemented by the `LegacyExtensionContext` class exported from\n  this new jsm module)\n\n- two new test files (an xpcshell-test and a mochitest-browser) ensures that the LegacyExtensionContext can receive a Port\n  object and exchange messages with a background page and a content script (the content script test\n  is in a different test file because it doesn't currently work on android, because it needs\n  the browser.tabs API and the TabManager internal helper)\n\nMozReview-Commit-ID: DS1NTXk0fB6", date=datetime.datetime(2016, 8, 24, 22, 1, 36), bug=b'', ever_backedout=False, author_email=b'lgreco@mozilla.com')
```

**Comment by marco-c** [comment]
So you're not seeing the original error anymore. This looks like a completely different error, not sure what's up.
