### ISSUE TITLE
Error While Installing

### ISSUE THREAD

**Issue by harshraj22** [mozilla/bugbug#2045]
## Screenshot
![a](https://user-images.githubusercontent.com/46635452/102716452-0f435a80-4302-11eb-9daa-3fcb508fe31a.png)

## Steps to reproduce error
run `pip3 install -r requirements.txt`

## Details:
I got the error while installation. Further trying to run `python -m scripts.trainer` ignoring the error while installation gives the following error:
```
Traceback (most recent call last):
  File "/opt/python/3.8.6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python/3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/codespace/workspace/bugbug/scripts/trainer.py", line 9, in <module>
    from bugbug import db
  File "/home/codespace/workspace/bugbug/bugbug/db.py", line 14, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'
```

**Comment by marco-c** [comment]
> `Python headers are required to build Mercurial but weren't found in /usr/include/python3.8/Python.h`

You need to install them (if you're on Debian or a Debian-based distro, `libpython3.8-dev` is the right package).
