### ISSUE TITLE
Error while training the model

### ISSUE THREAD

**Issue by ayush1999** [mozilla/bugbug#232]
It looks like a recent commit is breaking the training : `python run.py --train --goal=bug` gives me:
```
(bbug) ayush99@ayush99:~/GitHub/bugbug$ python run.py --train --goal=bug
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    from bugbug.models.bug import BugModel
  File "/home/ayush99/GitHub/bugbug/bugbug/models/bug.py", line 17, in <module>
    from bugbug.model import Model
  File "/home/ayush99/GitHub/bugbug/bugbug/model.py", line 17, in <module>
    from bugbug.nlp import SpacyVectorizer
  File "/home/ayush99/GitHub/bugbug/bugbug/nlp.py", line 17, in <module>
    nlp = spacy.load('en_core_web_sm')
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/spacy/util.py", line 131, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/spacy/util.py", line 152, in load_model_from_package
    return cls.load(**overrides)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/spacy/language.py", line 786, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/spacy/util.py", line 611, in from_disk
    reader(path / key)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/site-packages/spacy/language.py", line 776, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
  File "tokenizer.pyx", line 390, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 436, in spacy.tokenizer.Tokenizer.from_bytes
  File "/home/ayush99/GitHub/bbug/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/home/ayush99/GitHub/bbug/lib/python3.7/sre_parse.py", line 536, in _parse
    code1 = _class_escape(source, this)
  File "/home/ayush99/GitHub/bbug/lib/python3.7/sre_parse.py", line 337, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 257
```
@marco-c Can you confirm that this is actually a bug and not me unaware of something I should know?

**Comment by marco-c** [comment]
Make sure you updated the dependencies.
https://github.com/mozilla/bugbug/blob/937e889c517b040158ae2de0385db672114d2126/requirements.txt#L9 has been updated, and to update it with pip you need to uninstall it and reinstall it.

**Comment by ayush1999** [comment]
Ah, got it. Thanks!

**Comment by ShrikrishnaPatil** [comment]
Can You give me solution as i am facing same issue when i enter 
rasa train 
it gives error like above
