### ISSUE TITLE
Recent commit causes component model to raise error

### ISSUE THREAD

**Issue by ayush1999** [mozilla/bugbug#245]
The component model was working yesterday, when I tested it on colab. However, recent changes seem to be causing an AssertionError:
```
Traceback (most recent call last):
  File "run.py", line 70, in <module>
    model.train()
  File "/content/bugbug/bugbug/bugbug/model.py", line 77, in train
    X = self.extraction_pipeline.fit_transform(bugs())
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 298, in fit_transform
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 230, in _fit
    **fit_params_steps[name])
  File "/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/memory.py", line 342, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 614, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/base.py", line 464, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/content/bugbug/bugbug/bugbug/bug_features.py", line 383, in transform
    bug = bug_snapshot.rollback(bug, self.rollback_when)
  File "/content/bugbug/bugbug/bugbug/bug_snapshot.py", line 321, in rollback
    assert False, f'Current value for field {field} of {bug["id"]}:\n{bug[field]}\nis different from previous value:\n{new_value}'
AssertionError: Current value for field severity of 1307433:
normal
is different from previous value:
enhancement
```

**Comment by marco-c** [comment]
Are you sure you are on top of master? This issue has been fixed with 042b2aaacbbec217215802cd12d8109b6f1d69c4.
