### ISSUE TITLE
Failing to build on Apple M1

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#2855]
Running `pip install -r requirements.txt` gives the following error:

```
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      ~/repos/mozilla/bugbug/venv/bin/python /private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/ffi/build.py
      LLVM version... 13.0.1

      Traceback (most recent call last):
        File "/private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/ffi/build.py", line 220, in <module>
          main()
        File "/private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/ffi/build.py", line 214, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/ffi/build.py", line 172, in main_posix
          raise RuntimeError(msg)
      RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '13.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
      Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

      error: command '~/repos/mozilla/bugbug/venv/bin/python' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.38.0
    Uninstalling llvmlite-0.38.0:
      Successfully uninstalled llvmlite-0.38.0
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error

  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running install
      ~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      got version from file /private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/llvmlite/_version.py {'version': '0.36.0', 'full': 'e6bb8d137d922bec8beeb01a237254778759becd'}
      running build_ext
      ~/repos/mozilla/bugbug/venv/bin/python /private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/ffi/build.py
      LLVM version... 13.0.1

      Traceback (most recent call last):
        File "/private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/ffi/build.py", line 220, in <module>
          main()
        File "/private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/ffi/build.py", line 214, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/z4/12lcyr2n3c37kzjfksk6hwx40000gn/T/pip-install-045kded6/llvmlite_e0783b5b2e3b48288cdb7a651eb9c07b/ffi/build.py", line 172, in main_posix
          raise RuntimeError(msg)
      RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '13.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
      Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

      error: command '~/repos/mozilla/bugbug/venv/bin/python' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in ./venv/lib/python3.9/site-packages
  Rolling back uninstall of llvmlite
  Moving to ~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/llvmlite-0.38.0.dist-info/
   from ~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/~lvmlite-0.38.0.dist-info
  Moving to ~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/llvmlite/
   from ~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/~lvmlite
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

This happens because pip tries to build llvmlite `v0.36.0` in order to solve a dependency conflict on the version of NumPy.
Bugbug requires `numpy==1.22.3`. Howeber, Numba (a transitive dependency of `shap[plots]==0.40.0`) requires `numpy<=1.21`.

Using the `numpy==1.21.5` to satisfy `numpy` solve the issue and avoid building `llvmlite`. However, running `python3 -m scripts.trainer defect` gives the following error:

```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
```

I guess resolving https://github.com/numba/llvmlite/issues/799 could fix this issue since then we can have wheels for `llvmlite` and depend on the correct NumPy version.

**Comment by marco-c** [comment]
> Using the `numpy==1.21.5` to satisfy `numpy` solve the issue and avoid building `llvmlite`. However, running `python3 -m scripts.trainer defect` gives the following error:
> 
> ```
> RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
> ```

What is the module that is failing?
Is there any additional info in the stacktrace?

**Comment by suhaibmujahid** [comment]
> What is the module that is failing?

https://github.com/mozilla/bugbug/blob/cbaf0de92e96cdb287d461478312b32fc48ef4c1/bugbug/model.py#L12

> Is there any additional info in the stacktrace?

This is when using `numpy==1.22.3`:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "~/repos/mozilla/bugbug/scripts/trainer.py", line 11, in <module>
    from bugbug.models import MODELS, get_model_class
  File "~/repos/mozilla/bugbug/bugbug/models/__init__.py", line 6, in <module>
    from bugbug.model import Model
  File "~/repos/mozilla/bugbug/bugbug/model.py", line 12, in <module>
    import shap
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/shap/__init__.py", line 12, in <module>
    from ._explanation import Explanation, Cohorts
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/shap/_explanation.py", line 12, in <module>
    from .utils._general import OpChain
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/shap/utils/__init__.py", line 1, in <module>
    from ._clustering import hclust_ordering, partition_tree, partition_tree_shuffle, delta_minimization_order, hclust
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/shap/utils/_clustering.py", line 4, in <module>
    from numba import jit
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/numba/__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/numba/__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.21 or less")
ImportError: Numba needs NumPy 1.21 or less
```

This is when using `numpy==1.21.5`:

```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "~/repos/mozilla/bugbug/scripts/trainer.py", line 11, in <module>
    from bugbug.models import MODELS, get_model_class
  File "~/repos/mozilla/bugbug/bugbug/models/__init__.py", line 6, in <module>
    from bugbug.model import Model
  File "~/repos/mozilla/bugbug/bugbug/model.py", line 12, in <module>
    import shap
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/shap/__init__.py", line 12, in <module>
    from ._explanation import Explanation, Cohorts
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/shap/_explanation.py", line 12, in <module>
    from .utils._general import OpChain
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/shap/utils/__init__.py", line 1, in <module>
    from ._clustering import hclust_ordering, partition_tree, partition_tree_shuffle, delta_minimization_order, hclust
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/shap/utils/_clustering.py", line 4, in <module>
    from numba import jit
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/numba/core/extending.py", line 19, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "~/repos/mozilla/bugbug/venv/lib/python3.9/site-packages/numba/core/pythonapi.py", line 12, in <module>
    from numba import _helperlib
ImportError: numpy.core.multiarray failed to import
```
