### ISSUE TITLE
Failing to access the value of `code_analysis_server` when running multi processes on Mac

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3131]
The tests fail on Mac when running `test_repository.py`:
```
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/smujahid/repos/mozilla/bugbug/bugbug/repository.py", line 839, in _transform
    return transform(HG, REPO_DIR, commit)
  File "/Users/smujahid/repos/mozilla/bugbug/bugbug/repository.py", line 693, in transform
    assert code_analysis_server is not None
AssertionError
"""
```

**Comment by suhaibmujahid** [comment]
https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods:
> Changed in version 3.8: On macOS, the spawn start method is now the default.  The fork start method should be considered unsafe as it can lead to crashes of the subprocess.

Enforcing the start method to be `fork` (which is the default on Unix) instead of `spawn` solves the issue.
