### ISSUE TITLE
commit_classifier.py fails with testlabelselect

### ISSUE THREAD

**Issue by baolef** [mozilla/bugbug#3507]
I'm trying to run `commit_classifier.py` with model `testlabelselect` with
```
python -m scripts.commit_classifier testlabelselect ../mozilla-unified --revision 076c495bba18
```
However, an error occurs:
```
Traceback (most recent call last):
  File "/home/baole/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.5787.24/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/baole/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.5787.24/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/baole/research/libre/project/code/bugbug/scripts/commit_classifier.py", line 881, in <module>
    main()
  File "/home/baole/research/libre/project/code/bugbug/scripts/commit_classifier.py", line 877, in main
    classifier.classify(args.revision, args.runnable_jobs)
  File "/home/baole/research/libre/project/code/bugbug/scripts/commit_classifier.py", line 635, in classify
    self.classify_test_select(commits, runnable_jobs_path)
  File "/home/baole/research/libre/project/code/bugbug/scripts/commit_classifier.py", line 691, in classify_test_select
    selected_tasks = [
  File "/home/baole/research/libre/project/code/bugbug/scripts/commit_classifier.py", line 692, in <listcomp>
    t for t in selected_tasks if t.startswith("test-linux1804-64/")
AttributeError: 'float' object has no attribute 'startswith'
python-BaseException
```
It happens because `selected_tasks` is [a list of float](https://github.com/mozilla/bugbug/blob/master/bugbug/models/testselect.py#L585).

**Comment by marco-c** [comment]
@baolef this should now be fixed, though the commit_classifier.py script is not used in production and so is not as well maintained as the HTTP service. There might be other bugs hidden somewhere :)
