### ISSUE TITLE
swagger is broken

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#3875]
```
2023-12-01T14:26:38.680345+00:00 app[web.1]: 2023-12-01 14:26:38,679:ERROR:bugbug_http.app:Exception on /swagger [GET]
2023-12-01T14:26:38.680359+00:00 app[web.1]: Traceback (most recent call last):
2023-12-01T14:26:38.680368+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
2023-12-01T14:26:38.680368+00:00 app[web.1]:     response = self.full_dispatch_request()
2023-12-01T14:26:38.680369+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
2023-12-01T14:26:38.680369+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2023-12-01T14:26:38.680369+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
2023-12-01T14:26:38.680369+00:00 app[web.1]:     rv = self.dispatch_request()
2023-12-01T14:26:38.680370+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
2023-12-01T14:26:38.680370+00:00 app[web.1]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-12-01T14:26:38.680371+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
2023-12-01T14:26:38.680371+00:00 app[web.1]:     resp = make_response(f(*args, **kwargs))
2023-12-01T14:26:38.680371+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/bugbug_http/app.py", line 1050, in swagger
2023-12-01T14:26:38.680372+00:00 app[web.1]:     spec.path(view=rule)
2023-12-01T14:26:38.680372+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/apispec/core.py", line 534, in path
2023-12-01T14:26:38.680372+00:00 app[web.1]:     plugin.operation_helper(path=path, operations=operations, **kwargs)
2023-12-01T14:26:38.680372+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/apispec/ext/marshmallow/__init__.py", line 224, in operation_helper
2023-12-01T14:26:38.680373+00:00 app[web.1]:     self.resolver.resolve_operations(operations)
2023-12-01T14:26:38.680373+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/apispec/ext/marshmallow/schema_resolver.py", line 33, in resolve_operations
2023-12-01T14:26:38.680373+00:00 app[web.1]:     self.resolve_schema(operation["requestBody"])
2023-12-01T14:26:38.680374+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/apispec/ext/marshmallow/schema_resolver.py", line 231, in resolve_schema
2023-12-01T14:26:38.680374+00:00 app[web.1]:     content["schema"] = self.resolve_schema_dict(content["schema"])
2023-12-01T14:26:38.680374+00:00 app[web.1]:   File "/usr/local/lib/python3.10/site-packages/apispec/ext/marshmallow/schema_resolver.py", line 284, in resolve_schema_dict
2023-12-01T14:26:38.680375+00:00 app[web.1]:     for k, v in schema["properties"].items()
2023-12-01T14:26:38.680375+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by suhaibmujahid** [comment]
The `/doc` page also does not work because it depends on the `/swagger` page.

http://bugbug.herokuapp.com/doc


```
Something went wrong...
Failed to load http://bugbug.herokuapp.com/swagger: 500 INTERNAL SERVER ERROR

Stack trace

u@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:75657
4182/loadExternalRef/<@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:76783
s@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:74778

ReDoc Version: 2.0.0-rc.75
Commit: d7440fb
```
