### ISSUE TITLE
[model:regressor] AttributeError: 'IsotonicRegressionCalibrator' object has no attribute 'n_features_in_'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3909]
https://community-tc.services.mozilla.com/tasks/HncpjvKKRcSnxL_GJ8PV9A/runs/0/logs/public/logs/live.log
```
Traceback (most recent call last):
  File "/usr/local/bin/bugbug-train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/scripts/trainer.py", line 141, in main
    retriever.go(args)
  File "/usr/local/lib/python3.10/site-packages/scripts/trainer.py", line 41, in go
    metrics = model_obj.train(limit=args.limit)
  File "/usr/local/lib/python3.10/site-packages/bugbug/model.py", line 418, in train
    logger.info("Number of features: %d", self.clf.steps[-1][1].n_features_in_)
AttributeError: 'IsotonicRegressionCalibrator' object has no attribute 'n_features_in_'
```

**Comment by jpangas** [comment]
I think using the `n_features_in_` attribute from the `base_clf` should solve this.
`self.n_features_in_ = self.base_clf.n_features_in_`

**Comment by suhaibmujahid** [comment]
> I think using the `n_features_in_` attribute from the `base_clf` (after fitting) should solve this.

Yes. Let's solve it that way for now. But at some point, I think we should reconsider the way that we calibrate the model.
