### ISSUE TITLE
Try using XGBoost's support for multilabel classification instead of OneVsRestClassifier

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#404]
Part of #20.

**Comment by chidauri** [comment]
when running bugtype model , this is the error i get with confusion matrix :(

> X: (151023, 22897), y: (151023, 4)
Cross Validation scores:
Accuracy: f0.9721228442842706 (+/- 0.004838766883424093)
X_train: (15102, 22897), y_train: (15102, 4)
X_test: (1511, 22897), y_test: (1511, 4)
Test Set scores:
No confidence threshold - 1511 classified
Traceback (most recent call last):
  File "run.py", line 159, in <module>
    main(parse_args(sys.argv[1:]))
  File "run.py", line 90, in main
    model.train()
  File "/home/harshit/Documents/bugbug/bugbug/model.py", line 256, in train
    confusion_matrix = metrics.confusion_matrix(y_test, y_pred, labels=class_names)
  File "/home/harshit/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 255, in confusion_matrix
    raise ValueError("%s is not supported" % y_type)
ValueError: multilabel-indicator is not supported

**Comment by marco-c** [comment]
@chidauri could you file a new issue about this error?
