### ISSUE TITLE
Failing to send the weekly quality report

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#4465]
See https://community-tc.services.mozilla.com/tasks/NywYRmm-TDGzjGaDbacs6w/runs/0/logs/public/logs/live.log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugbug/phabricator.py", line 61, in <lambda>
    lambda PHABRICATOR_API=PHABRICATOR_API: PHABRICATOR_API.request(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/libmozdata/phabricator.py", line 670, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://phabricator.services.mozilla.com/api/transaction.search
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/bugbug-generate-landings-risk-report", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scripts/generate_landings_risk_report.py", line 1882, in main
    landings_risk_report_generator.go(args.days)
  File "/usr/local/lib/python3.12/site-packages/scripts/generate_landings_risk_report.py", line 892, in go
    self.generate_landings_by_date(bug_map, bugs, self.get_blocking_of(meta_bugs))
  File "/usr/local/lib/python3.12/site-packages/scripts/generate_landings_risk_report.py", line 492, in generate_landings_by_date
    phabricator.download_modified_revisions()
  File "/usr/local/lib/python3.12/site-packages/bugbug/phabricator.py", line 154, in download_modified_revisions
    modified_revisions = get(modified_start=last_modified)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugbug/phabricator.py", line 114, in get
    revision["transactions"] = get_transactions(revision["phid"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugbug/phabricator.py", line 57, in get_transactions
    out = tenacity.retry(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x74a3efb85c10 state=finished raised HTTPError>]
```

@jensstutte reported multiple times that he did not receive the report:
- June 18, 2024
- August 27, 2024
- September 3, 2024

**Comment by jensstutte** [comment]
The last weeks again I had no reports, the latest I find is from Sep 17 (I was on PTO in between).

**Comment by marco-c** [comment]
There are a couple of bugs I need to fix, working on them slowly.

**Comment by marco-c** [comment]
This should be working now.
