### ISSUE TITLE
Bug classification can choke on a single bug when giving a list

### ISSUE THREAD

**Issue by Lothiraldan** [mozilla/bugbug#450]
When calling `model.classify` with a list of bug data, a single bug might trigger a error like the following one:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 799, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 600, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 606, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./bugbug_http_service/models.py", line 101, in classify_bug
    probs = model.classify(list(bugs.values()), True)
  File "/usr/local/lib/python3.7/site-packages/bugbug/model.py", line 191, in classify
    X = self.extraction_pipeline.transform(items)
  File "/usr/local/lib/python3.7/site-packages/sklearn/pipeline.py", line 540, in _transform
    Xt = transform.transform(Xt)
  File "/usr/local/lib/python3.7/site-packages/bugbug/bug_features.py", line 431, in transform
    bug = bug_snapshot.rollback(bug, self.rollback_when)
  File "/usr/local/lib/python3.7/site-packages/bugbug/bug_snapshot.py", line 600, in rollback
    ), f'Current value for field {field} of {bug["id"]}:\n{bug[field]}\nis different from previous value:\n{new_value}'
AssertionError: Current value for field product of 812809:
```
As we are classifying a batch, it is problematic as no other bugs in the batch will be classified.

https://github.com/mozilla/bugbug/pull/321/files#diff-7908c821177e4af7e08af4a9ca055d60R99

**Comment by marco-c** [comment]
When rollbacking the bug, we shouldn't fail when a field is inconsistent, but rather remove the field altogether and consider it as missing data.
