### ISSUE TITLE
check-component task is failing to load component model

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#468]
From https://tools.taskcluster.net/groups/TPcM3XbjR0mSz4qGwJmqyA/tasks/YX85nWDWS8iUTJ1qZk0I2Q/runs/0/logs/public%2Flogs%2Flive.log:
```
Traceback (most recent call last):
  File "/usr/local/bin/bugbug-check", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/scripts/check.py", line 52, in main
    checker.go(args.model)
  File "/usr/local/lib/python3.7/site-packages/scripts/check.py", line 32, in go
    model = model_class.load(model_file_name)
  File "/usr/local/lib/python3.7/site-packages/bugbug/model.py", line 173, in load
    return joblib.load(model_file_name)
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 590, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'componentmodel'
```

**Comment by marco-c** [comment]
Should be fixed with #452.

**Comment by marco-c** [comment]
Should have been fixed, but it is still happening.

**Comment by marco-c** [comment]
Unless the task wrongly used the old image, I guess with tagging we will be able to tell.

**Comment by marco-c** [comment]
> Unless the task wrongly used the old image, I guess with tagging we will be able to tell.

Actually, the task did use the new image, we can tell from the line numbers in the stack trace.

So, looking at the logs, I see the model was not downloaded. Probably the environment variables were not set.
