### ISSUE TITLE
I get an error when running bugbug in auto_nag

### ISSUE THREAD

**Issue by calixteman** [mozilla/bugbug#481]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/component.py", line 7, in <module>
    from bugbug.models.component import ComponentModel
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.6/site-packages/bugbug/models/component.py", line 13, in <module>
    from bugbug import bug_features, bugzilla, feature_cleanup
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.6/site-packages/bugbug/bug_features.py", line 14, in <module>
    from bugbug import bug_snapshot, repository
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.6/site-packages/bugbug/repository.py", line 19, in <module>
    import rs_parsepatch
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/rm_bot/relman-auto-nag/venv/lib/python3.6/site-packages/rs_parsepatch.cpython-36m-x86_64-linux-gnu.so)

The glibc version in the vm is 2.17

I think repository should be loaded lazily to avoid such an error (afaik repository stuff is useless for auto_nag)

**Comment by calixteman** [comment]
An easy workaround is to add in repository.py:
```python
try:
    import rs_parsepatch
except:
    pass
```
