### ISSUE TITLE
Docker HTTP build task is failing

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#504]
Regression from #458.

```
+ python http_service/download_models.py
Traceback (most recent call last):
  File "http_service/download_models.py", line 7, in <module>
    from models import MODELS_NAMES, retrieve_model
  File "/code/http_service/models.py", line 14, in <module>
    from bugbug.models import load_model as bugbug_load_model
ModuleNotFoundError: No module named 'bugbug'
```

**Comment by Lothiraldan** [comment]
I think the error is older than merging #458, any bugbug import would fails when building the http Docker Image as it's running in the taskboot image and not bugbug itself. I need to think about the best way to do that.
