### ISSUE TITLE
HTTP service deployment task is failing

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#572]
The artifact filter no longer applies, since https://github.com/mozilla/task-boot/pull/38.

```
+ taskboot deploy-heroku --artifact-filter public/bugbug/bugbug-http-service.tar --heroku-app bugbug
INFO:root:Target setup in /tmp/taskboot.k250s3ky
WARNING:taskboot.target:No target cloned
INFO:root:Loading Taskcluster secret project/relman/bugbug/deploy
INFO:taskboot.utils:Loading task status DeVGOTYdSwG08123izCWKQ
INFO:taskboot.utils:Loading task dependencies 1/2 OxYmgsNsS9aqkCx-bRgvUQ
INFO:taskboot.utils:Loading task dependencies 2/2 TgBnKDsyQrCK1KCe-hR9jQ
Traceback (most recent call last):
  File "/usr/local/bin/taskboot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/taskboot/cli.py", line 231, in main
    args.func(target, args)
  File "/usr/local/lib/python3.7/site-packages/taskboot/push.py", line 81, in heroku_release
    raise ValueError(f"No artifact found for {args.artifact_filter}")
ValueError: No artifact found for public/bugbug/bugbug-http-service.tar
```

**Comment by La0** [comment]
Task boot needs unit tests to avoid such regressions :(

**Comment by marco-c** [comment]
Yeah, even though this is mostly an issue with how bugbug is using task-boot rather than in task-boot itself.
