### ISSUE TITLE
MemoryError while training defect model

### ISSUE THREAD

**Issue by probaku1234** [mozilla/bugbug#620]

**Comment by marco-c** [comment]
Can you provide more details? When are you seeing the MemoryError exactly? What command/script did you run?

**Comment by probaku1234** [comment]
When I run `python run.py --train`, I get this error
 ```
Traceback (most recent call last):
  File "run.py", line 147, in <module>
    main(parse_args(sys.argv[1:]))
  File "run.py", line 81, in main
    model.train()
  File "E:\pikapika\project\bugbug\bugbug\model.py", line 99, in train
    scores = cross_validate(pipeline, X_train, y_train, scoring=scorings, cv=5)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 231, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\joblib\parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\joblib\parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\joblib\parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\joblib\_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\joblib\_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\joblib\parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\joblib\parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 514, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\imblearn\pipeline.py", line 237, in fit
    Xt, yt, fit_params = self._fit(X, y, **fit_params)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\imblearn\pipeline.py", line 200, in _fit
    cloned_transformer, Xt, yt, **fit_params_steps[name])
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\joblib\memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\imblearn\pipeline.py", line 576, in _fit_resample_one
    X_res, y_res = sampler.fit_resample(X, y, **fit_params)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\imblearn\base.py", line 85, in fit_resample
    output = self._fit_resample(X, y)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\imblearn\over_sampling\_smote.py", line 335, in _fit_resample
    return self._sample(X, y)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\imblearn\over_sampling\_smote.py", line 351, in _sample
    self.nn_m_, X_class, class_sample, y, kind='danger')
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\imblearn\over_sampling\_smote.py", line 212, in _in_danger_noise
    x = nn_estimator.kneighbors(samples, return_distance=False)[:, 1:]
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\sklearn\neighbors\base.py", line 434, in kneighbors
    **kwds))
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\sklearn\metrics\pairwise.py", line 1448, in pairwise_distances_chunked
    n_jobs=n_jobs, **kwds)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\sklearn\metrics\pairwise.py", line 1588, in pairwise_distances
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\sklearn\metrics\pairwise.py", line 1206, in _parallel_pairwise
    return func(X, Y, **kwds)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\sklearn\metrics\pairwise.py", line 273, in euclidean_distances
    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\sklearn\utils\extmath.py", line 137, in safe_sparse_dot
    ret = a * b
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\scipy\sparse\base.py", line 481, in __mul__
    return self._mul_sparse_matrix(other)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\scipy\sparse\compressed.py", line 517, in _mul_sparse_matrix
    data = np.empty(nnz, dtype=upcast(self.dtype, other.dtype))
MemoryError
````

**Comment by marco-c** [comment]
OK, so it's not while downloading databases, but while training.

**Comment by marco-c** [comment]
How much RAM do you have?

**Comment by probaku1234** [comment]
Mine is 16 GB

**Comment by marco-c** [comment]
Mmmh, pretty strange that it's running out of memory then. One way to avoid it is removing this line: https://github.com/mozilla/bugbug/blob/bed338ba1cafac8c7d4708e1d522fe8365af5696/bugbug/models/defect.py#L22.

**Comment by probaku1234** [comment]
After removing that line, I get this error
```
Traceback (most recent call last):
  File "run.py", line 147, in <module>
    main(parse_args(sys.argv[1:]))
  File "run.py", line 81, in main
    model.train()
  File "E:\pikapika\project\bugbug\bugbug\model.py", line 124, in train
    shap_values = explainer.shap_values(X_train)
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\shap\explainers\tree.py", line 177, in shap_values
    approx_contribs=approximate, validate_features=False
  File "E:\pikapika\project\bugbug\venv\lib\site-packages\xgboost\core.py", line 1292, in predict
    ctypes.byref(preds)))
OSError: [WinError -529697949] Windows Error 0xe06d7363
```

**Comment by marco-c** [comment]
Add `self.calculate_feature_importances = False`.

**Comment by probaku1234** [comment]
add that line to where exactly?

**Comment by marco-c** [comment]
Where you removed the previous one

**Comment by probaku1234** [comment]
Hm...I'm still getting same error with above code

**Comment by marco-c** [comment]
Sorry, the correct attribute to set to False is self.calculate_importance, not the one I told you before.

**Comment by probaku1234** [comment]
It worked! Thank you
