### ISSUE TITLE
HTTP service deployment is failing

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#667]
From https://tools.taskcluster.net/groups/LxTuw6rUTs-B2PPzIEBtyA/tasks/eG9eMHmMT1W2dJlLPrbO9g/runs/0/logs/public%2Flogs%2Flive.log:
```
INFO:taskboot.push:Deploying update for dyno types: ['web', 'worker']
Traceback (most recent call last):
  File "/usr/local/bin/taskboot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/taskboot/cli.py", line 234, in main
    args.func(target, args)
  File "/usr/local/lib/python3.7/site-packages/taskboot/push.py", line 141, in heroku_release
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.heroku.com/apps/bugbug/formation
```

**Comment by Lothiraldan** [comment]
I've made a PR on task-boot https://github.com/mozilla/task-boot/pull/49 to fix the deployment. Unfortunately I wasn't able to test it locally, I always get a 401 even with the right secret.

**Comment by marco-c** [comment]
This was fixed.
