### ISSUE TITLE
Error when running bugbug-classify-commit without cache

### ISSUE THREAD

**Issue by Lothiraldan** [mozilla/bugbug#671]
When running `bugbug-classify-commit` without cache (I don't have the file `data/commit_experiences.pickle` locally), I got an exception:

```
Using TensorFlow backend.
.../.virtualenvs/mozilla-automl-3.7/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
INFO:gensim.summarization.textcleaner:'pattern' package not found; tag filters are not available for English
Spacy model is missing, install it with: .../.virtualenvs/mozilla-automl-3.7/bin/python3.7 -m spacy download en_core_web_sm
INFO:bugbug.repository:Pulling and updating mozilla-central
INFO:bugbug.repository:mozilla-central pulled and updated
Downloading https://index.taskcluster.net/v1/task/project.relman.bugbug.data_commits.latest/artifacts/public/commits.json.version to data/commits.json.version
Getting revs from children(51440617724b12fec25ba05b0b2e25241c92683e) to tip...
Mining 2085 commits using 4 processes...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:27<00:00,  3.04s/it]
Downloading file->component mapping...
2085 commits to ignore
Analyzing experiences from 2085 commits...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2085/2085 [00:00<00:00, 1328037.03it/s]
  0%|                                                                                                                                                                                       | 0/2085 [00:00<?, ?it/s]
Traceback (most recent call last):
  File ".../.virtualenvs/mozilla-automl-3.7/bin/bugbug-classify-commit", line 11, in <module>
    load_entry_point('bugbug', 'console_scripts', 'bugbug-classify-commit')()
  File ".../project/mozilla-automl/bugbug/scripts/commit_classifier.py", line 141, in main
    classifier.classify(args.diff_id)
  File ".../project/mozilla-automl/bugbug/scripts/commit_classifier.py", line 94, in classify
    self.update_commit_db()
  File ".../project/mozilla-automl/bugbug/scripts/commit_classifier.py", line 54, in update_commit_db
    repository.download_commits(self.repo_dir, rev_start)
  File ".../project/mozilla-automl/bugbug/bugbug/repository.py", line 705, in download_commits
    calculate_experiences(commits, commits_to_ignore, first_pushdate, save)
  File ".../project/mozilla-automl/bugbug/bugbug/repository.py", line 571, in calculate_experiences
    if orig_directory in experiences["directory"][commit_type]:
KeyError: 'directory'
```

**Comment by marco-c** [comment]
That's strange, it should be downloaded automatically.

**Comment by marco-c** [comment]
Can you do a `rm -f data/commit*` to make sure there is nothing half-downloaded in your data directory?

**Comment by Lothiraldan** [comment]
Removing everything in commit makes it download the support file, closing this issue
