### ISSUE TITLE
Try using doc2vec as similarity algorithm

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#674]
After #637, we should try with doc2vec too and see what works better.

**Comment by Goku2699** [comment]
@marco-c   is this issue resolved or still on? I'm new to open source so need your help to make some contributions.

**Comment by marco-c** [comment]
No, it's not resolved yet. It depends on #637, so that one must be fixed first before fixing this one.
Once that is fixed, something similar needs to be done but using doc2vec instead of word2vec.

**Comment by ayush-1506** [comment]
@Goku2699 #637 is done. Feel free to give this a try.

**Comment by probaku1234** [comment]
I'm trying to run the word2vec code, but `bugzilla.get_bugs()` in init function returns nothing and because of that error pops up.

**Comment by marco-c** [comment]
You should train a model first, so that the bugs DB will be downloaded.
```
python3 run.py --goal defect --train
```

**Comment by probaku1234** [comment]
I downloaded db with that code but still it gets nothing.

**Comment by marco-c** [comment]
Can you post the output of `ls -al data/`?
What error pops up?

Try to give as much info as possible, otherwise it'll be hard to help you :)

**Comment by probaku1234** [comment]
This is the result of ls
```
total 6278256
drwxr-xr-x  10 yunseoblee  staff         320 Jul  2 14:22 .
drwxr-xr-x  34 yunseoblee  staff        1088 Jul 12 22:25 ..
-rw-r--r--   1 yunseoblee  staff  1410490733 Jul  2 14:22 bugs.json
-rw-r--r--   1 yunseoblee  staff           1 Jun 21 15:53 bugs.json.version
-rw-r--r--   1 yunseoblee  staff   235073932 Jul  2 14:22 bugs.json.zst
-rw-r--r--   1 yunseoblee  staff          34 Jul  2 14:22 bugs.json.zst.etag
-rw-r--r--   1 yunseoblee  staff  1398900302 Jul  2 14:22 commits.json
-rw-r--r--   1 yunseoblee  staff           1 Jun 21 15:53 commits.json.version
-rw-r--r--   1 yunseoblee  staff   150652308 Jul  2 14:22 commits.json.zst
-rw-r--r--   1 yunseoblee  staff          34 Jul  2 14:22 commits.json.zst.etag
```
This is the error traceback
```
Traceback (most recent call last):
  File "/Users/yunseoblee/Desktop/bugbug/scripts/evaluate_similarity.py", line 38, in <module>
    main(parse_args(sys.argv[1:]))
  File "/Users/yunseoblee/Desktop/bugbug/scripts/evaluate_similarity.py", line 32, in main
    model = Word2VecWmdSimilarity()
  File "/Users/yunseoblee/Desktop/bugbug/bugbug/similarity.py", line 201, in __init__
    self.w2vmodel = Word2Vec(self.corpus, size=100, min_count=5)
  File "/Users/yunseoblee/Desktop/bugbug/venv/lib/python3.7/site-packages/gensim/models/word2vec.py", line 783, in __init__
    fast_version=FAST_VERSION)
  File "/Users/yunseoblee/Desktop/bugbug/venv/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 763, in __init__
    end_alpha=self.min_alpha, compute_loss=compute_loss)
  File "/Users/yunseoblee/Desktop/bugbug/venv/lib/python3.7/site-packages/gensim/models/word2vec.py", line 910, in train
    queue_factor=queue_factor, report_delay=report_delay, compute_loss=compute_loss, callbacks=callbacks)
  File "/Users/yunseoblee/Desktop/bugbug/venv/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 1081, in train
    **kwargs)
  File "/Users/yunseoblee/Desktop/bugbug/venv/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 536, in train
    total_words=total_words, **kwargs)
  File "/Users/yunseoblee/Desktop/bugbug/venv/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 1187, in _check_training_sanity
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model
```

**Comment by ayush-1506** [comment]
@probaku1234 Are you in the correct directory? `bugzilla.get_bugs()` works only when you are in `bugbug/`. From the root directory of this project, run `python scripts/evaluate_similarity.py --algorithm=word2vec_wmd`.

**Comment by probaku1234** [comment]
If I run `python scripts/evaluate_similarity.py --algorithm=word2vec_wmd` or `python3 scripts/evaluate_similarity.py --algorithm=word2vec_wmd`, I get the error below
```
Traceback (most recent call last):
  File "scripts/evaluate_similarity.py", line 11, in <module>
    from bugbug.similarity import LSISimilarity, NeighborsSimilarity, Word2VecWmdSimilarity
ModuleNotFoundError: No module named 'bugbug'
```

**Comment by ayush-1506** [comment]
@probaku1234 Have you added bugbug to you pythonpath? If you're on linux, open the .bashrc file and add
`export PYTHONPATH=path_to_bugbug_directory`.

**Comment by probaku1234** [comment]
@ayush-1506 So....the error is gone now. But output on console shows below result and the program keep running. 
```
INFO:gensim.summarization.textcleaner:'pattern' package not found; tag filters are not available for English
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/yunseoblee/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
```

**Comment by ayush-1506** [comment]
@probaku1234 Yes! That's because the vocabulary is pretty bug, so it takes time to build the word2vec model. For testing, you can use a smaller portion of the bug dataset.

**Comment by probaku1234** [comment]
@ayush-1506  Oh..I see. Then how can I set to use small portion of the dataset?

**Comment by ayush-1506** [comment]
@probaku1234 Add  `from itertools import islice`in the similarity.py file and replace https://github.com/mozilla/bugbug/blob/master/bugbug/similarity.py#L191 with `for bug in islice(bugzilla.get_bugs(), 15000)`, so this will use only the first 15000 bugs.

**Comment by ayush-1506** [comment]
(There isn't an option, you'll have to do it manually)

**Comment by aditya-hari** [comment]
> @probaku1234 Are you in the correct directory? `bugzilla.get_bugs()` works only when you are in `bugbug/`. From the root directory of this project, run `python scripts/evaluate_similarity.py --algorithm=word2vec_wmd`.

@ayush-1506   
I get the following error on trying to run that command -   

```
Traceback (most recent call last):
  File "/home/lemvig/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lemvig/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lemvig/Desktop/github/bugbug/scripts/trainer.py", line 123, in <module>
    main()
  File "/home/lemvig/Desktop/github/bugbug/scripts/trainer.py", line 119, in main
    retriever.go(args)
  File "/home/lemvig/Desktop/github/bugbug/scripts/trainer.py", line 60, in go
    metrics = model_obj.train()
  File "/home/lemvig/Desktop/github/bugbug/bugbug/model.py", line 317, in train
    classes, self.class_names = self.get_labels()
AttributeError: 'BugModel' object has no attribute 'get_labels'
 
```   
 
What do I do?

**Comment by ayush-1506** [comment]
@aditya-hari Are you on master? Looks like you're a few commits behind master.

**Comment by aditya-hari** [comment]
Oh whoops, sorry. Didn't notice. Will get back to you soon.

**Comment by aditya-hari** [comment]
> You should train a model first, so that the bugs DB will be downloaded.
> 
> ```
> python3 run.py --goal defect --train
> ```

Has that changed now, because I can't find a run.py...

**Comment by marco-c** [comment]
Yes, there is a trainer script now (see the README for updated info).

**Comment by sd1998** [comment]
@marco-c I would like to work on this.

**Comment by marco-c** [comment]
@sd1998 feel free to work on any open issue (following the rules in CONTRIBUTING.md), no need to ask.

**Comment by Divya063** [comment]
@sd1998  Are you still working on the issue?

**Comment by marco-c** [comment]
@Divya063 all issues are unassigned until there is a PR open to fix them, so feel free to work on this if it's interesting for you.

**Comment by srajgure** [comment]
@marco-c  I would like to work on this problem. Can you please provide some details on how to approach it? I'm new to open source contribution.

**Comment by marco-c** [comment]
@srajgure there is quite a few info in this issue report, just read through the comments.

**Comment by bhushan-borole** [comment]
Hello @marco-c 
I have read the above discussions.
In order to fix this issue, I will have to create a class `Word2VecSimilarity` that extends `Word2VecSimilarityBase`.
Am I right?

**Comment by marco-c** [comment]
It might be better to add an option to the already existing word2vec classes to use doc2vec instead of word2vec (in the end they're very similar).

**Comment by rock420** [comment]
@marco-c Hi there! I would love to work on this issue if the issue is still relevant.
I have gone through the scripts of similarity algorithms (more specifically the word2vec implementation) to get insight into the project. I have few queries regarding the implementation of doc2vec -

1.  Should I use the **PV-DM** doc2vec algorithm? (default algorithm in `gensim`)
2.  Would you like to have the **cosine similarity** of document vectors as the similarity function between two docs?

**Comment by marco-c** [comment]
Hello @rock420, sorry for the delay!

1. Yes, but we can try other algorithms to find the best.
2. Yes, but as 1, we can try other similarity metrics to find the best.

**Comment by rock420** [comment]
ok. I will do that.

> It might be better to add an option to the already existing word2vec classes to use doc2vec instead of word2vec (in the end they're very similar).

Regarding this, will not it be better to have a separate implementation of doc2vec? For classes like [`Word2VecWmdSimilarity`](https://github.com/mozilla/bugbug/blob/master/bugbug/similarity.py#L393) and [`Word2VecWmdRelaxSimilarity`](https://github.com/mozilla/bugbug/blob/master/bugbug/similarity.py#L536), we can not have an option for doc2vec as WMD is based on word embeddings. And again for the class [`Word2VecSoftCosSimilarity`](https://github.com/mozilla/bugbug/blob/master/bugbug/similarity.py#L644) if we are keeping an option, we need to use many `if else` blocks in-between.
In my view, extending the [`Word2VecSimilarityBase`](https://github.com/mozilla/bugbug/blob/master/bugbug/similarity.py#L364)  class to create a separate `doc2vec` class (following the Single Responsibility Principle) will make it less ambiguous.

Would like to know your thoughts on this.

**Comment by marco-c** [comment]
@rock420 yeah, a separate class sounds like the best idea.

**Comment by marco-c** [comment]
(Though it should still be possible to use WMD with doc2vec!)

**Comment by rock420** [comment]
@marco-c, yeah we can use the word embeddings which are also learned during the doc2vec training. Then, should I keep the `doc2vec` option for WMD classes?

**Comment by marco-c** [comment]
Yeah, I'd say yes.
