### ISSUE TITLE
Failure when getting bugs last change time

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#797]
```
2019-07-26T22:38:19.259010+00:00 app[web.1]: ERROR:http_service.app:Exception on /component/predict/batch [POST]

2019-07-26T22:38:19.259026+00:00 app[web.1]: Traceback (most recent call last):

2019-07-26T22:38:19.259029+00:00 app[web.1]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app

2019-07-26T22:38:19.259031+00:00 app[web.1]:     response = self.full_dispatch_request()

2019-07-26T22:38:19.259034+00:00 app[web.1]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request

2019-07-26T22:38:19.259036+00:00 app[web.1]:     rv = self.handle_user_exception(e)

2019-07-26T22:38:19.259038+00:00 app[web.1]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception

2019-07-26T22:38:19.259041+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)

2019-07-26T22:38:19.259043+00:00 app[web.1]:   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise

2019-07-26T22:38:19.259045+00:00 app[web.1]:     raise value

2019-07-26T22:38:19.259047+00:00 app[web.1]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request

2019-07-26T22:38:19.259050+00:00 app[web.1]:     rv = self.dispatch_request()

2019-07-26T22:38:19.259052+00:00 app[web.1]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request

2019-07-26T22:38:19.259054+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)

2019-07-26T22:38:19.259057+00:00 app[web.1]:   File "/usr/local/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function

2019-07-26T22:38:19.259059+00:00 app[web.1]:     resp = make_response(f(*args, **kwargs))

2019-07-26T22:38:19.259061+00:00 app[web.1]:   File "/code/http_service/app.py", line 388, in batch_prediction

2019-07-26T22:38:19.259063+00:00 app[web.1]:     bug_change_dates = get_bugs_last_change_time(bugs)

2019-07-26T22:38:19.259065+00:00 app[web.1]:   File "/code/http_service/app.py", line 144, in get_bugs_last_change_time

2019-07-26T22:38:19.259068+00:00 app[web.1]:     raw_bugs = response.json()

2019-07-26T22:38:19.259070+00:00 app[web.1]:   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json

2019-07-26T22:38:19.259072+00:00 app[web.1]:     return complexjson.loads(self.text, **kwargs)

2019-07-26T22:38:19.259074+00:00 app[web.1]:   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads

2019-07-26T22:38:19.259076+00:00 app[web.1]:     return _default_decoder.decode(s)

2019-07-26T22:38:19.259078+00:00 app[web.1]:   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode

2019-07-26T22:38:19.259080+00:00 app[web.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())

2019-07-26T22:38:19.259082+00:00 app[web.1]:   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode

2019-07-26T22:38:19.259085+00:00 app[web.1]:     raise JSONDecodeError("Expecting value", s, err.value) from None

2019-07-26T22:38:19.259086+00:00 app[web.1]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Lothiraldan** [comment]
That's the kind of failure we get when the query string is too big for Bugzilla. https://github.com/mozilla/bugbug/pull/794 will enforce the batch size and I will work on the best way to detect such situation.

**Comment by marco-c** [comment]
We could chunk the Bugzilla query.

**Comment by Lothiraldan** [comment]
It should be fixed by https://github.com/mozilla/bugbug/pull/794 at least temporarily. When the bug ids will start to reach around 1,000,000, the query string will get too big and we will need to batch the calls to Bugzilla anyway.

**Comment by Lothiraldan** [comment]
I can add code detecting when bugzilla is not returning JSON but what should we do in this case? Ignore the bugs change time and returns what we have in database? Returns a 500 to the caller?

Bugzilla can returns non-JSON in other cases too, it can be down for example.

**Comment by marco-c** [comment]
I think we're safer if we return 500 in those cases.

**Comment by Lothiraldan** [comment]
Got it, I will return a 500
